[package]
name = "zellij-foreman"
version = "0.1.2"
edition = "2024"

[dependencies]
regex = "1.12.3"
zellij-tile = "0.43.1"

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true
